version: "2.2"
services:
  ####  nginx 反向代理 ####
  nginx_proxy: 
    container_name: nginx_proxy
    image: dodomogu/adsame:nginx
    ports:
      - "80:80"
    volumes:
      - /Volumes/html:/var/www:cached                          # 代码目录
      - ./etc/nginx_proxy/nginx.conf:/etc/nginx/nginx.conf    # 主配置文件
      - ./etc/nginx_proxy/conf.d:/etc/nginx/conf.d            # 虚拟域名配置目录
      - ./log/nginx_proxy:/var/log/nginx                      # 日志目录
    networks:
      webnet:
        ipv4_address: 172.19.0.2
    depends_on: 
      - nginx
    links:
      - nginx
  ###### nginx 1.16.1 ######
  nginx:
    container_name: nginx
    image: dodomogu/adsame:nginx
    expose:
      - 80  # php54
      - 81  # php72
      - 82  # php53
      - 83  # php53
      - 85  # php74
      - 84  # laravel
    # ports:
    #   - "8086:80"  #dolphin.com
    #   - "8087:81"  #dolphin-72.com
    #   # - "8088:82"  #songtang.net
    # extra_hosts:
      # - dolphin-72.com:127.0.0.1
      # - dolphin.com:127.0.0.1
      # - yun.localsongtang.net:127.0.0.1
      # - login.localsongtang.net:127.0.0.1
      # - ucenter.localsongtang.net:127.0.0.1
    volumes:
      - /Volumes/html:/var/www:cached                          # 代码目录
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf    # 主配置文件
      - ./etc/nginx/conf.d:/etc/nginx/conf.d            # 虚拟域名配置目录
      - ./log/nginx:/var/log/nginx                      # 日志目录
    networks:
      webnet:
        ipv4_address: 172.19.0.3
    links:
      - php54
      - php72
      - php74
      - php53
      - laravel
    depends_on: 
      - php54
      - php72
      - php74
      - php53
      - laravel
  ##### php5.4.16 #####
  php54:
    container_name: php54
    image: dodomogu/adsame:php54
    volumes:
      - /Volumes/html:/var/www                # 代码目录
      - ./etc/php54/php.ini:/etc/php.ini      # php主配置
      - ./etc/php54/php.d:/etc/php.d          # php模块配置
      - ./etc/php54/php-fpm.conf:/etc/php-fpm.conf      # php-fpm主配置
      - ./etc/php54/php-fpm.d:/etc/php-fpm.d      # php-fpm模块配置
      - ./log/php54:/var/log/php-fpm          # 日志目录
      - ./session/php54:/var/lib/php/session  # session目录
    expose:
      - 9000
    networks:
      webnet:
        ipv4_address: 172.19.0.4
    # links:
      # - mysql
  #### php7.2.24  #######
  php72:
    container_name: php72
    image: dodomogu/adsame:php72
    volumes:
      - /Volumes/html:/var/www:cached
      - ./etc/php72/php.ini:/etc/php.ini      # php主配置
      - ./etc/php72/php.d:/etc/php.d          # php模块配置
      - ./etc/php72/php-fpm.conf:/etc/php-fpm.conf      # php-fpm主配置
      - ./etc/php72/php-fpm.d:/etc/php-fpm.d      # php-fpm模块配置
      - ./log/php72:/var/log/php-fpm          # 日志目录
      - ./log/php72/samedataweblog:/data/weblog
      - ./session/php72:/var/lib/php/session  # session目录
    extra_hosts: 
      - dolphin-72.com:172.19.0.1
      - samedata-api.com:172.19.0.1
    expose:
      - 9000
    networks:
      webnet:
        ipv4_address: 172.19.0.5
    # links:
    #   - mysql
  #### php5.3.3 #####
  php53:
    container_name: php53
    image: dodomogu/adsame:php53
    # image: php53test:latest
    volumes:
      - /Volumes/html:/var/www:cached                # 代码目录
      - ./etc/php53/php.ini:/etc/php.ini      # php主配置
      - ./etc/php53/php.d:/etc/php.d          # php模块配置
      - ./etc/php53/php-fpm.conf:/etc/php-fpm.conf      # php-fpm主配置
      - ./etc/php53/php-fpm.d:/etc/php-fpm.d      # php-fpm模块配置
      - ./log/php53:/var/log/php-fpm          # 日志目录
      - ./session/php53:/var/lib/php/session  # session目录
    expose:
      - 9000
    networks:
      webnet:
        ipv4_address: 172.19.0.8
    # links:
    #   - mysql
  ##### php5.6.40 #####
  php56:
    container_name: php56
    image: dodomogu/adsame:php56
    volumes:
      - /Volumes/html:/var/www:cached                # 代码目录
      - ./etc/php56/php.ini:/etc/php.ini      # php主配置
      - ./etc/php56/php.d:/etc/php.d          # php模块配置
      - ./etc/php56/php-fpm.conf:/etc/php-fpm.conf      # php-fpm主配置
      - ./etc/php56/php-fpm.d:/etc/php-fpm.d      # php-fpm模块配置
      - ./log/php56:/var/log/php-fpm          # 日志目录
      - ./log/php56/samedataweblog:/data/weblog/
      - ./session/php56:/var/lib/php/session  # session目录
    expose:
      - 9000
    networks:
      webnet:
        ipv4_address: 172.19.0.11
    # links:
      # - mysql
  #### laravel (php7.2.31)  #######
  laravel:
    container_name: laravel
    image: dodomogu/adsame:laravel
    volumes:
      - /Volumes/html:/var/www:cached
      - ./etc/laravel/php.ini:/etc/opt/remi/php74/php.ini      # php主配置
      - ./etc/laravel/php.d:/etc/opt/remi/php74/php.d          # php模块配置
      - ./etc/laravel/php-fpm.conf:/etc/opt/remi/php74/php-fpm.conf      # php-fpm主配置
      - ./etc/laravel/php-fpm.d:/etc/opt/remi/php74/php-fpm.d      # php-fpm模块配置
      - ./log/laravel:/var/opt/remi/php74/log/php-fpm          # 日志目录
      - ./session/laravel:/var/opt/remi/php74/lib/php/session  # session目录
    expose:
      - 9000
    networks:
      webnet:
        ipv4_address: 172.19.0.13
    # links:
    #   - mysql
  #### php7.4.8  #######
  php74:
    container_name: php74
    # image: dodomogu/adsame:php72
    image: php74
    volumes:
      - /Volumes/html:/var/www:cached
      - ./etc/php74/php.ini:/etc/opt/remi/php74/php.ini      # php主配置
      - ./etc/php74/php.d:/etc/opt/remi/php74/php.d          # php模块配置
      - ./etc/php74/php-fpm.conf:/etc/opt/remi/php74/php-fpm.conf      # php-fpm主配置
      - ./etc/php74/php-fpm.d:/etc/opt/remi/php74/php-fpm.d      # php-fpm模块配置
      - ./log/php74:/var/opt/remi/php74/log/php-fpm          # 日志目录
      - ./log/php74/samedataweblog:/data/weblog/
      - ./session/php74:/var/opt/remi/php74/lib/php/session  # session目录
    # extra_hosts: 
    #   - dolphin-72.com:172.19.0.1
    expose:
      - 9000
    networks:
      webnet:
        ipv4_address: 172.19.0.14
  redis:
    container_name: redis
    image: redis:latest
    expose: 
      - 6379
    networks:
      webnet:
        ipv4_address: 172.19.0.12
  # mysql:
  #   container_name: mysql
  #   image: mysql:test
  #   volumes:
  #     - /Volumes/html/mysqldata:/var/lib/mysql      # data目录
  #     # - ./etc/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf  #配置文件
  #     - ./log/mysql:/var/log/mysql                  # 日志目录
  #   environment:
  #     MYSQL_ROOT_PASSWORD: gljgogo
  #     MYSQL_DATABASE: test
  #     MYSQL_USER: gljgljglj
  #     MYSQL_PASSWORD: gljgogo
  #   expose:
  #     - 3306
  #   networks:
  #     webnet:
  #       ipv4_address: 172.19.0.6
  node:
    container_name: node
    image: dodomogu/adsame:node  #node:12
    working_dir: /var/www
    # command: npm run start
    # ports:
    #   - "8086:80"  #dolphin.com
    #   - "8087:81"  #dolphin-72.com
    tty: true
    volumes:
      - /Volumes/html:/var/www:cached     
      # - ./etc/mysql:/etc/mysql        
      # - ./log/node:/var/log/node                 # 日志目录
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "3000:3000"
    extra_hosts: 
      - dolphin-72.com:172.19.0.1
      - samedata-api.com:172.19.0.1
    # expose:
    #   - 8080
    networks:
      webnet:
        ipv4_address: 172.19.0.7
  # java:
  #   container_name: java
  #   image: java
  #   tty: true
  #   # ports:
  #   #   - "8086:80"  #dolphin.com
  #   #   - "8087:81"  #dolphin-72.com
  #   volumes:
  #     - /Volumes/html/docker/java:/var/www     
  #     # - ./etc/mysql:/etc/mysql        
  #     # - ./log/node:/var/log/node                 # 日志目录
  #   extra_hosts: 
  #       - dolphin-72.com:172.19.0.1
  #   networks:
  #     webnet:
  #       ipv4_address: 172.19.0.9
  # python:
  #   container_name: python
  #   image: python:latest
  #   tty: true
  #   volumes:
  #     - /Volumes/html/docker/python:/var/www    
  #   networks:
  #     webnet:
  #       ipv4_address: 172.19.0.10
networks:
  webnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1